CREATE LOGIN [headbutton]
    WITH PASSWORD = N';nvrj?hWudamm|=;ngddBLcymsFT7_&#$!~<zsskNrubhtTC', SID = 0x633628B4752DFE4A9D5BD9307F7EF5A6, DEFAULT_DATABASE = [NORTHWND], DEFAULT_LANGUAGE = [us_english], CHECK_POLICY = OFF;

